### ISSUE TITLE
Filter Out Unpublished Inventory Items

### ISSUE THREAD

**Issue by nickoliver86** [excellalabs/wagtail-xima#8]
As of right now, the products and inventory pages are retrieved from `InventoryItem.objects.all()`

We need to either do an object filter to those items which are currently in the published state or check in some other way to prevent unpublished products from appearing in lists. Use case might be a seasonal item that becomes "published" and "unpublished" during certain times of the year when it's produced and not, respectively.

**Comment by kurtrwall** [comment]
http://docs.wagtail.io/en/v1.1/reference/pages/queryset_reference.html#wagtail.wagtailcore.query.PageQuerySet.live
